# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.building.build_main import Analysis, PYZ, EXE, COLLECT
import os

block_cipher = None

# When running from backend directory, paths are relative
# The spec file is in backend/, and frontend is in ../frontend
a = Analysis(
    ['build_entry.py'],
    pathex=[os.getcwd()],
    binaries=[],
    datas=[
        ('app', 'app'),
        (r'..\frontend\dist', r'frontend'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'win32api',
        'win32con',
        'win32process',
        'win32security',
        'win32event',
        'win32gui',
        'winerror',
        'pydantic',
        'pydantic.v1',
        'pydantic_settings',
        'pydantic.deprecated',
        'pydantic.deprecated.decorator',
        'pydantic_core',
        'fastapi',
        'fastapi.routing',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'fastapi.responses',
        'fastapi.dependencies',
        'fastapi.dependencies.utils',
        'fastapi.openapi',
        'fastapi.openapi.docs',
        'fastapi.exception_handlers',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.middleware.errors',
        'starlette.middleware.exceptions',
        'starlette.staticfiles',
        'starlette.responses',
        'starlette.requests',
        'starlette.applications',
        'starlette.concurrency',
        'starlette.datastructures',
        'starlette.exceptions',
        'starlette.types',
        'starlette.websockets',
        'starlette._exception_handler',
        'starlette._utils',
        'toml',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'h11',
        'email_validator',
        'typing_extensions',
        'idna',
        'sniffio',
        'qrcode',
        'qrcode.constants',
        'qrcode.image',
        'qrcode.image.base',
        'qrcode.image.svg',
        'qrcode.main',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'PIL',
        'scipy',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'tkinter',
        'unittest',
        'test',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='QuantumSwitch',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Set to False for windowed mode, True for console output
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r'.\icon.ico',  # Application icon
)
